### PR TITLE
Support shorthand property assignment in object literals

### PR DESCRIPTION
**Pull request by gakada**

### CODE REVIEW

**Comment by gakada** [comment]
Seems like travis is happy, though locally I have
```
Pass: 464/578
Fail: 114/578
```
because of https://github.com/Perryvw/TypescriptToLua/issues/186
```
Error: LUA ERROR: error loading module 'lualib_bundle' from file './lualib_bundle.lua':./lualib_bundle.lua:436: <eof> expected near 'function'
```

**Comment by Perryvw** [comment]
I would still like a test `const myfield = 3; const myobject = {myfield}; return myobject.myfield` expecting 3. After that I am fine with merging this.

**Comment by gakada** [comment]
Oh there is `executeLua` as well. Where should I add it?

**Comment by gakada** [comment]
Added in ObjectLiteralTests as well since it is not exactly an assignment.

**Comment by Perryvw** [comment]
`test/unit/objectLiteral.spec.ts` is fine.

**Pull request merged**
