### PR TITLE
Add multiple argument support to array.push()

### PR DESCRIPTION
**Pull request by zapp-brannigan-dota**
If this is accepted the wiki can be updated too.

### CODE REVIEW

**Comment by lolleko** [comment]
Might be better to do that in lualib instead of hacking it into the translation.

**Comment by zapp-brannigan-dota** [comment]
Yeah that's much cleaner.

**Comment by lolleko** [comment]
Might also be better to use `tbl[#tbl + 1] = "newValue"` instead of table.insert since its faster. Opinions @Perryvw?

**Comment by Perryvw** [comment]
If `tbl[#tbl + 1]` is faster I don't see why not.

**Comment by lolleko** [comment]
I think JIT probably already optimises that, but its defiantly faster on other Lua versions.

**Pull request merged**
